"""
Configuration settings for the Revolut Trading App
Complete list of all Revolut-supported cryptocurrencies and stocks
"""

# All Revolut-supported cryptocurrencies (comprehensive list)
REVOLUT_CRYPTOS = [
    # Major Cryptocurrencies
    {"symbol": "BTC", "name": "Bitcoin", "coingecko_id": "bitcoin"},
    {"symbol": "ETH", "name": "Ethereum", "coingecko_id": "ethereum"},
    {"symbol": "XRP", "name": "Ripple", "coingecko_id": "ripple"},
    {"symbol": "LTC", "name": "Litecoin", "coingecko_id": "litecoin"},
    {"symbol": "BCH", "name": "Bitcoin Cash", "coingecko_id": "bitcoin-cash"},
    {"symbol": "XLM", "name": "Stellar", "coingecko_id": "stellar"},
    {"symbol": "EOS", "name": "EOS", "coingecko_id": "eos"},
    {"symbol": "DOGE", "name": "Dogecoin", "coingecko_id": "dogecoin"},
    {"symbol": "ADA", "name": "Cardano", "coingecko_id": "cardano"},
    {"symbol": "DOT", "name": "Polkadot", "coingecko_id": "polkadot"},
    {"symbol": "SOL", "name": "Solana", "coingecko_id": "solana"},
    {"symbol": "AVAX", "name": "Avalanche", "coingecko_id": "avalanche-2"},
    {"symbol": "MATIC", "name": "Polygon", "coingecko_id": "matic-network"},
    {"symbol": "SHIB", "name": "Shiba Inu", "coingecko_id": "shiba-inu"},
    {"symbol": "ATOM", "name": "Cosmos", "coingecko_id": "cosmos"},
    {"symbol": "NEAR", "name": "NEAR Protocol", "coingecko_id": "near"},
    {"symbol": "TRX", "name": "TRON", "coingecko_id": "tron"},
    {"symbol": "ETC", "name": "Ethereum Classic", "coingecko_id": "ethereum-classic"},

    # DeFi Tokens
    {"symbol": "UNI", "name": "Uniswap", "coingecko_id": "uniswap"},
    {"symbol": "LINK", "name": "Chainlink", "coingecko_id": "chainlink"},
    {"symbol": "AAVE", "name": "Aave", "coingecko_id": "aave"},
    {"symbol": "CRV", "name": "Curve DAO", "coingecko_id": "curve-dao-token"},
    {"symbol": "LDO", "name": "Lido DAO", "coingecko_id": "lido-dao"},
    {"symbol": "MKR", "name": "Maker", "coingecko_id": "maker"},
    {"symbol": "SNX", "name": "Synthetix", "coingecko_id": "havven"},
    {"symbol": "COMP", "name": "Compound", "coingecko_id": "compound-governance-token"},
    {"symbol": "1INCH", "name": "1inch", "coingecko_id": "1inch"},
    {"symbol": "SUSHI", "name": "SushiSwap", "coingecko_id": "sushi"},
    {"symbol": "YFI", "name": "yearn.finance", "coingecko_id": "yearn-finance"},
    {"symbol": "BAL", "name": "Balancer", "coingecko_id": "balancer"},
    {"symbol": "DYDX", "name": "dYdX", "coingecko_id": "dydx"},
    {"symbol": "GMX", "name": "GMX", "coingecko_id": "gmx"},
    {"symbol": "FXS", "name": "Frax Share", "coingecko_id": "frax-share"},
    {"symbol": "RPL", "name": "Rocket Pool", "coingecko_id": "rocket-pool"},
    {"symbol": "PENDLE", "name": "Pendle", "coingecko_id": "pendle"},

    # Layer 2 & Scaling
    {"symbol": "ARB", "name": "Arbitrum", "coingecko_id": "arbitrum"},
    {"symbol": "OP", "name": "Optimism", "coingecko_id": "optimism"},
    {"symbol": "IMX", "name": "Immutable X", "coingecko_id": "immutable-x"},
    {"symbol": "LRC", "name": "Loopring", "coingecko_id": "loopring"},
    {"symbol": "METIS", "name": "Metis", "coingecko_id": "metis-token"},
    {"symbol": "SKL", "name": "SKALE", "coingecko_id": "skale"},
    {"symbol": "STRK", "name": "Starknet", "coingecko_id": "starknet"},

    # Gaming & Metaverse
    {"symbol": "SAND", "name": "The Sandbox", "coingecko_id": "the-sandbox"},
    {"symbol": "MANA", "name": "Decentraland", "coingecko_id": "decentraland"},
    {"symbol": "APE", "name": "ApeCoin", "coingecko_id": "apecoin"},
    {"symbol": "AXS", "name": "Axie Infinity", "coingecko_id": "axie-infinity"},
    {"symbol": "GALA", "name": "Gala", "coingecko_id": "gala"},
    {"symbol": "ENJ", "name": "Enjin Coin", "coingecko_id": "enjincoin"},
    {"symbol": "ILV", "name": "Illuvium", "coingecko_id": "illuvium"},
    {"symbol": "RNDR", "name": "Render", "coingecko_id": "render-token"},
    {"symbol": "BLUR", "name": "Blur", "coingecko_id": "blur"},
    {"symbol": "MAGIC", "name": "Magic", "coingecko_id": "magic"},
    {"symbol": "PRIME", "name": "Echelon Prime", "coingecko_id": "echelon-prime"},

    # Infrastructure & Oracles
    {"symbol": "GRT", "name": "The Graph", "coingecko_id": "the-graph"},
    {"symbol": "FIL", "name": "Filecoin", "coingecko_id": "filecoin"},
    {"symbol": "AR", "name": "Arweave", "coingecko_id": "arweave"},
    {"symbol": "STORJ", "name": "Storj", "coingecko_id": "storj"},
    {"symbol": "API3", "name": "API3", "coingecko_id": "api3"},
    {"symbol": "BAND", "name": "Band Protocol", "coingecko_id": "band-protocol"},
    {"symbol": "OCEAN", "name": "Ocean Protocol", "coingecko_id": "ocean-protocol"},

    # Smart Contract Platforms
    {"symbol": "ALGO", "name": "Algorand", "coingecko_id": "algorand"},
    {"symbol": "XTZ", "name": "Tezos", "coingecko_id": "tezos"},
    {"symbol": "FTM", "name": "Fantom", "coingecko_id": "fantom"},
    {"symbol": "HBAR", "name": "Hedera", "coingecko_id": "hedera-hashgraph"},
    {"symbol": "EGLD", "name": "MultiversX", "coingecko_id": "elrond-erd-2"},
    {"symbol": "ICP", "name": "Internet Computer", "coingecko_id": "internet-computer"},
    {"symbol": "FLOW", "name": "Flow", "coingecko_id": "flow"},
    {"symbol": "KAVA", "name": "Kava", "coingecko_id": "kava"},
    {"symbol": "INJ", "name": "Injective", "coingecko_id": "injective-protocol"},
    {"symbol": "SEI", "name": "Sei", "coingecko_id": "sei-network"},
    {"symbol": "SUI", "name": "Sui", "coingecko_id": "sui"},
    {"symbol": "APT", "name": "Aptos", "coingecko_id": "aptos"},
    {"symbol": "CELO", "name": "Celo", "coingecko_id": "celo"},
    {"symbol": "ROSE", "name": "Oasis Network", "coingecko_id": "oasis-network"},
    {"symbol": "MINA", "name": "Mina Protocol", "coingecko_id": "mina-protocol"},
    {"symbol": "KDA", "name": "Kadena", "coingecko_id": "kadena"},
    {"symbol": "ZIL", "name": "Zilliqa", "coingecko_id": "zilliqa"},
    {"symbol": "ONE", "name": "Harmony", "coingecko_id": "harmony"},
    {"symbol": "KLAY", "name": "Klaytn", "coingecko_id": "klay-token"},
    {"symbol": "VET", "name": "VeChain", "coingecko_id": "vechain"},
    {"symbol": "THETA", "name": "Theta Network", "coingecko_id": "theta-token"},
    {"symbol": "NEO", "name": "Neo", "coingecko_id": "neo"},
    {"symbol": "QTUM", "name": "Qtum", "coingecko_id": "qtum"},
    {"symbol": "WAVES", "name": "Waves", "coingecko_id": "waves"},
    {"symbol": "XEM", "name": "NEM", "coingecko_id": "nem"},
    {"symbol": "IOTA", "name": "IOTA", "coingecko_id": "iota"},
    {"symbol": "ZEC", "name": "Zcash", "coingecko_id": "zcash"},
    {"symbol": "XMR", "name": "Monero", "coingecko_id": "monero"},
    {"symbol": "DASH", "name": "Dash", "coingecko_id": "dash"},

    # AI & Data Tokens
    {"symbol": "FET", "name": "Fetch.ai", "coingecko_id": "fetch-ai"},
    {"symbol": "AGIX", "name": "SingularityNET", "coingecko_id": "singularitynet"},
    {"symbol": "WLD", "name": "Worldcoin", "coingecko_id": "worldcoin-wld"},
    {"symbol": "TAO", "name": "Bittensor", "coingecko_id": "bittensor"},
    {"symbol": "ARKM", "name": "Arkham", "coingecko_id": "arkham"},

    # Meme Coins
    {"symbol": "PEPE", "name": "Pepe", "coingecko_id": "pepe"},
    {"symbol": "FLOKI", "name": "Floki", "coingecko_id": "floki"},
    {"symbol": "BONK", "name": "Bonk", "coingecko_id": "bonk"},
    {"symbol": "WIF", "name": "dogwifhat", "coingecko_id": "dogwifcoin"},
    {"symbol": "MEME", "name": "Memecoin", "coingecko_id": "memecoin-2"},

    # Exchange Tokens
    {"symbol": "BNB", "name": "BNB", "coingecko_id": "binancecoin"},
    {"symbol": "CRO", "name": "Cronos", "coingecko_id": "crypto-com-chain"},
    {"symbol": "OKB", "name": "OKB", "coingecko_id": "okb"},
    {"symbol": "LEO", "name": "UNUS SED LEO", "coingecko_id": "leo-token"},
    {"symbol": "KCS", "name": "KuCoin Token", "coingecko_id": "kucoin-shares"},
    {"symbol": "GT", "name": "Gate Token", "coingecko_id": "gatechain-token"},

    # Other Notable Tokens
    {"symbol": "ENS", "name": "Ethereum Name Service", "coingecko_id": "ethereum-name-service"},
    {"symbol": "OMG", "name": "OMG Network", "coingecko_id": "omisego"},
    {"symbol": "QNT", "name": "Quant", "coingecko_id": "quant-network"},
    {"symbol": "CHZ", "name": "Chiliz", "coingecko_id": "chiliz"},
    {"symbol": "HOT", "name": "Holo", "coingecko_id": "holotoken"},
    {"symbol": "ZRX", "name": "0x Protocol", "coingecko_id": "0x"},
    {"symbol": "BAT", "name": "Basic Attention Token", "coingecko_id": "basic-attention-token"},
    {"symbol": "ANKR", "name": "Ankr", "coingecko_id": "ankr"},
    {"symbol": "RLC", "name": "iExec RLC", "coingecko_id": "iexec-rlc"},
    {"symbol": "MASK", "name": "Mask Network", "coingecko_id": "mask-network"},
    {"symbol": "SSV", "name": "ssv.network", "coingecko_id": "ssv-network"},
    {"symbol": "AUDIO", "name": "Audius", "coingecko_id": "audius"},
    {"symbol": "JASMY", "name": "JasmyCoin", "coingecko_id": "jasmycoin"},
    {"symbol": "STX", "name": "Stacks", "coingecko_id": "blockstack"},
    {"symbol": "RUNE", "name": "THORChain", "coingecko_id": "thorchain"},
    {"symbol": "CFX", "name": "Conflux", "coingecko_id": "conflux-token"},
    {"symbol": "OSMO", "name": "Osmosis", "coingecko_id": "osmosis"},
    {"symbol": "AKT", "name": "Akash Network", "coingecko_id": "akash-network"},
    {"symbol": "TIA", "name": "Celestia", "coingecko_id": "celestia"},
    {"symbol": "PYTH", "name": "Pyth Network", "coingecko_id": "pyth-network"},
    {"symbol": "JTO", "name": "Jito", "coingecko_id": "jito-governance-token"},
    {"symbol": "JUP", "name": "Jupiter", "coingecko_id": "jupiter-exchange-solana"},
    {"symbol": "W", "name": "Wormhole", "coingecko_id": "wormhole"},
    {"symbol": "ONDO", "name": "Ondo", "coingecko_id": "ondo-finance"},
    {"symbol": "ENA", "name": "Ethena", "coingecko_id": "ethena"},
    {"symbol": "EIGEN", "name": "EigenLayer", "coingecko_id": "eigenlayer"},
]

# All Revolut-supported stocks (comprehensive list)
REVOLUT_STOCKS = [
    # ===== TECHNOLOGY =====
    # FAANG & Big Tech
    {"symbol": "AAPL", "name": "Apple Inc.", "sector": "Technology"},
    {"symbol": "MSFT", "name": "Microsoft Corporation", "sector": "Technology"},
    {"symbol": "GOOGL", "name": "Alphabet Inc. Class A", "sector": "Technology"},
    {"symbol": "GOOG", "name": "Alphabet Inc. Class C", "sector": "Technology"},
    {"symbol": "AMZN", "name": "Amazon.com Inc.", "sector": "Technology"},
    {"symbol": "META", "name": "Meta Platforms Inc.", "sector": "Technology"},
    {"symbol": "NFLX", "name": "Netflix Inc.", "sector": "Technology"},

    # Semiconductors
    {"symbol": "NVDA", "name": "NVIDIA Corporation", "sector": "Technology"},
    {"symbol": "AMD", "name": "Advanced Micro Devices", "sector": "Technology"},
    {"symbol": "INTC", "name": "Intel Corporation", "sector": "Technology"},
    {"symbol": "TSM", "name": "Taiwan Semiconductor", "sector": "Technology"},
    {"symbol": "AVGO", "name": "Broadcom Inc.", "sector": "Technology"},
    {"symbol": "QCOM", "name": "Qualcomm Inc.", "sector": "Technology"},
    {"symbol": "TXN", "name": "Texas Instruments", "sector": "Technology"},
    {"symbol": "MU", "name": "Micron Technology", "sector": "Technology"},
    {"symbol": "MRVL", "name": "Marvell Technology", "sector": "Technology"},
    {"symbol": "KLAC", "name": "KLA Corporation", "sector": "Technology"},
    {"symbol": "LRCX", "name": "Lam Research", "sector": "Technology"},
    {"symbol": "AMAT", "name": "Applied Materials", "sector": "Technology"},
    {"symbol": "ASML", "name": "ASML Holding", "sector": "Technology"},
    {"symbol": "ARM", "name": "Arm Holdings", "sector": "Technology"},
    {"symbol": "ON", "name": "ON Semiconductor", "sector": "Technology"},
    {"symbol": "ADI", "name": "Analog Devices", "sector": "Technology"},
    {"symbol": "NXPI", "name": "NXP Semiconductors", "sector": "Technology"},
    {"symbol": "SWKS", "name": "Skyworks Solutions", "sector": "Technology"},
    {"symbol": "MCHP", "name": "Microchip Technology", "sector": "Technology"},

    # Software & Cloud
    {"symbol": "CRM", "name": "Salesforce Inc.", "sector": "Technology"},
    {"symbol": "ORCL", "name": "Oracle Corporation", "sector": "Technology"},
    {"symbol": "ADBE", "name": "Adobe Inc.", "sector": "Technology"},
    {"symbol": "NOW", "name": "ServiceNow Inc.", "sector": "Technology"},
    {"symbol": "INTU", "name": "Intuit Inc.", "sector": "Technology"},
    {"symbol": "SNOW", "name": "Snowflake Inc.", "sector": "Technology"},
    {"symbol": "PANW", "name": "Palo Alto Networks", "sector": "Technology"},
    {"symbol": "CRWD", "name": "CrowdStrike Holdings", "sector": "Technology"},
    {"symbol": "ZS", "name": "Zscaler Inc.", "sector": "Technology"},
    {"symbol": "FTNT", "name": "Fortinet Inc.", "sector": "Technology"},
    {"symbol": "DDOG", "name": "Datadog Inc.", "sector": "Technology"},
    {"symbol": "MDB", "name": "MongoDB Inc.", "sector": "Technology"},
    {"symbol": "NET", "name": "Cloudflare Inc.", "sector": "Technology"},
    {"symbol": "WDAY", "name": "Workday Inc.", "sector": "Technology"},
    {"symbol": "TEAM", "name": "Atlassian Corporation", "sector": "Technology"},
    {"symbol": "HUBS", "name": "HubSpot Inc.", "sector": "Technology"},
    {"symbol": "SPLK", "name": "Splunk Inc.", "sector": "Technology"},
    {"symbol": "OKTA", "name": "Okta Inc.", "sector": "Technology"},
    {"symbol": "ZM", "name": "Zoom Video Communications", "sector": "Technology"},
    {"symbol": "TWLO", "name": "Twilio Inc.", "sector": "Technology"},
    {"symbol": "DOCU", "name": "DocuSign Inc.", "sector": "Technology"},
    {"symbol": "TTD", "name": "The Trade Desk", "sector": "Technology"},
    {"symbol": "VEEV", "name": "Veeva Systems", "sector": "Technology"},
    {"symbol": "BILL", "name": "Bill Holdings", "sector": "Technology"},
    {"symbol": "MNDY", "name": "Monday.com", "sector": "Technology"},
    {"symbol": "PATH", "name": "UiPath Inc.", "sector": "Technology"},
    {"symbol": "U", "name": "Unity Software", "sector": "Technology"},
    {"symbol": "RBLX", "name": "Roblox Corporation", "sector": "Technology"},
    {"symbol": "S", "name": "SentinelOne", "sector": "Technology"},
    {"symbol": "CFLT", "name": "Confluent Inc.", "sector": "Technology"},
    {"symbol": "GTLB", "name": "GitLab Inc.", "sector": "Technology"},
    {"symbol": "ESTC", "name": "Elastic N.V.", "sector": "Technology"},
    {"symbol": "FROG", "name": "JFrog Ltd.", "sector": "Technology"},

    # Internet & E-commerce
    {"symbol": "SHOP", "name": "Shopify Inc.", "sector": "Technology"},
    {"symbol": "BKNG", "name": "Booking Holdings", "sector": "Technology"},
    {"symbol": "ABNB", "name": "Airbnb Inc.", "sector": "Technology"},
    {"symbol": "UBER", "name": "Uber Technologies", "sector": "Technology"},
    {"symbol": "LYFT", "name": "Lyft Inc.", "sector": "Technology"},
    {"symbol": "DASH", "name": "DoorDash Inc.", "sector": "Technology"},
    {"symbol": "SNAP", "name": "Snap Inc.", "sector": "Technology"},
    {"symbol": "PINS", "name": "Pinterest Inc.", "sector": "Technology"},
    {"symbol": "SPOT", "name": "Spotify Technology", "sector": "Technology"},
    {"symbol": "EBAY", "name": "eBay Inc.", "sector": "Technology"},
    {"symbol": "ETSY", "name": "Etsy Inc.", "sector": "Technology"},
    {"symbol": "CHWY", "name": "Chewy Inc.", "sector": "Technology"},
    {"symbol": "YELP", "name": "Yelp Inc.", "sector": "Technology"},
    {"symbol": "MTCH", "name": "Match Group", "sector": "Technology"},
    {"symbol": "BMBL", "name": "Bumble Inc.", "sector": "Technology"},
    {"symbol": "RDDT", "name": "Reddit Inc.", "sector": "Technology"},
    {"symbol": "DUOL", "name": "Duolingo Inc.", "sector": "Technology"},

    # Hardware & Devices
    {"symbol": "CSCO", "name": "Cisco Systems", "sector": "Technology"},
    {"symbol": "IBM", "name": "IBM Corporation", "sector": "Technology"},
    {"symbol": "HPQ", "name": "HP Inc.", "sector": "Technology"},
    {"symbol": "HPE", "name": "Hewlett Packard Enterprise", "sector": "Technology"},
    {"symbol": "DELL", "name": "Dell Technologies", "sector": "Technology"},
    {"symbol": "WDC", "name": "Western Digital", "sector": "Technology"},
    {"symbol": "STX", "name": "Seagate Technology", "sector": "Technology"},
    {"symbol": "PSTG", "name": "Pure Storage", "sector": "Technology"},
    {"symbol": "NTAP", "name": "NetApp Inc.", "sector": "Technology"},
    {"symbol": "LOGI", "name": "Logitech International", "sector": "Technology"},

    # AI & Data Analytics
    {"symbol": "PLTR", "name": "Palantir Technologies", "sector": "Technology"},
    {"symbol": "AI", "name": "C3.ai Inc.", "sector": "Technology"},
    {"symbol": "BBAI", "name": "BigBear.ai Holdings", "sector": "Technology"},
    {"symbol": "UPST", "name": "Upstart Holdings", "sector": "Technology"},
    {"symbol": "SOUN", "name": "SoundHound AI", "sector": "Technology"},

    # ===== AUTOMOTIVE =====
    {"symbol": "TSLA", "name": "Tesla Inc.", "sector": "Automotive"},
    {"symbol": "F", "name": "Ford Motor Company", "sector": "Automotive"},
    {"symbol": "GM", "name": "General Motors", "sector": "Automotive"},
    {"symbol": "RIVN", "name": "Rivian Automotive", "sector": "Automotive"},
    {"symbol": "LCID", "name": "Lucid Group", "sector": "Automotive"},
    {"symbol": "NIO", "name": "NIO Inc.", "sector": "Automotive"},
    {"symbol": "XPEV", "name": "XPeng Inc.", "sector": "Automotive"},
    {"symbol": "LI", "name": "Li Auto Inc.", "sector": "Automotive"},
    {"symbol": "FSR", "name": "Fisker Inc.", "sector": "Automotive"},
    {"symbol": "TM", "name": "Toyota Motor", "sector": "Automotive"},
    {"symbol": "HMC", "name": "Honda Motor", "sector": "Automotive"},
    {"symbol": "STLA", "name": "Stellantis N.V.", "sector": "Automotive"},
    {"symbol": "RACE", "name": "Ferrari N.V.", "sector": "Automotive"},
    {"symbol": "APTV", "name": "Aptiv PLC", "sector": "Automotive"},
    {"symbol": "BWA", "name": "BorgWarner Inc.", "sector": "Automotive"},
    {"symbol": "LEA", "name": "Lear Corporation", "sector": "Automotive"},

    # ===== FINANCE & FINTECH =====
    # Banks
    {"symbol": "JPM", "name": "JPMorgan Chase", "sector": "Finance"},
    {"symbol": "BAC", "name": "Bank of America", "sector": "Finance"},
    {"symbol": "WFC", "name": "Wells Fargo", "sector": "Finance"},
    {"symbol": "C", "name": "Citigroup Inc.", "sector": "Finance"},
    {"symbol": "GS", "name": "Goldman Sachs", "sector": "Finance"},
    {"symbol": "MS", "name": "Morgan Stanley", "sector": "Finance"},
    {"symbol": "USB", "name": "U.S. Bancorp", "sector": "Finance"},
    {"symbol": "PNC", "name": "PNC Financial", "sector": "Finance"},
    {"symbol": "TFC", "name": "Truist Financial", "sector": "Finance"},
    {"symbol": "SCHW", "name": "Charles Schwab", "sector": "Finance"},
    {"symbol": "BK", "name": "Bank of New York Mellon", "sector": "Finance"},
    {"symbol": "STT", "name": "State Street Corp", "sector": "Finance"},
    {"symbol": "FITB", "name": "Fifth Third Bancorp", "sector": "Finance"},
    {"symbol": "KEY", "name": "KeyCorp", "sector": "Finance"},
    {"symbol": "CFG", "name": "Citizens Financial", "sector": "Finance"},
    {"symbol": "HBAN", "name": "Huntington Bancshares", "sector": "Finance"},
    {"symbol": "RF", "name": "Regions Financial", "sector": "Finance"},

    # Investment & Asset Management
    {"symbol": "BLK", "name": "BlackRock Inc.", "sector": "Finance"},
    {"symbol": "BX", "name": "Blackstone Inc.", "sector": "Finance"},
    {"symbol": "KKR", "name": "KKR & Co.", "sector": "Finance"},
    {"symbol": "APO", "name": "Apollo Global Management", "sector": "Finance"},
    {"symbol": "ARES", "name": "Ares Management", "sector": "Finance"},
    {"symbol": "CG", "name": "Carlyle Group", "sector": "Finance"},
    {"symbol": "TROW", "name": "T. Rowe Price", "sector": "Finance"},
    {"symbol": "IVZ", "name": "Invesco Ltd.", "sector": "Finance"},
    {"symbol": "BEN", "name": "Franklin Resources", "sector": "Finance"},
    {"symbol": "AMG", "name": "Affiliated Managers", "sector": "Finance"},

    # Payment & Fintech
    {"symbol": "V", "name": "Visa Inc.", "sector": "Fintech"},
    {"symbol": "MA", "name": "Mastercard Inc.", "sector": "Fintech"},
    {"symbol": "AXP", "name": "American Express", "sector": "Fintech"},
    {"symbol": "PYPL", "name": "PayPal Holdings", "sector": "Fintech"},
    {"symbol": "SQ", "name": "Block Inc.", "sector": "Fintech"},
    {"symbol": "COIN", "name": "Coinbase Global", "sector": "Fintech"},
    {"symbol": "HOOD", "name": "Robinhood Markets", "sector": "Fintech"},
    {"symbol": "AFRM", "name": "Affirm Holdings", "sector": "Fintech"},
    {"symbol": "SOFI", "name": "SoFi Technologies", "sector": "Fintech"},
    {"symbol": "NU", "name": "Nu Holdings", "sector": "Fintech"},
    {"symbol": "FIS", "name": "Fidelity National Info", "sector": "Fintech"},
    {"symbol": "FISV", "name": "Fiserv Inc.", "sector": "Fintech"},
    {"symbol": "GPN", "name": "Global Payments", "sector": "Fintech"},
    {"symbol": "ADYEN", "name": "Adyen N.V.", "sector": "Fintech"},
    {"symbol": "MELI", "name": "MercadoLibre Inc.", "sector": "Fintech"},
    {"symbol": "DFS", "name": "Discover Financial", "sector": "Fintech"},
    {"symbol": "COF", "name": "Capital One Financial", "sector": "Fintech"},
    {"symbol": "SYF", "name": "Synchrony Financial", "sector": "Fintech"},

    # Insurance
    {"symbol": "BRK.B", "name": "Berkshire Hathaway B", "sector": "Finance"},
    {"symbol": "AIG", "name": "American International Group", "sector": "Finance"},
    {"symbol": "MET", "name": "MetLife Inc.", "sector": "Finance"},
    {"symbol": "PRU", "name": "Prudential Financial", "sector": "Finance"},
    {"symbol": "AFL", "name": "Aflac Inc.", "sector": "Finance"},
    {"symbol": "TRV", "name": "Travelers Companies", "sector": "Finance"},
    {"symbol": "ALL", "name": "Allstate Corp", "sector": "Finance"},
    {"symbol": "PGR", "name": "Progressive Corp", "sector": "Finance"},
    {"symbol": "CB", "name": "Chubb Limited", "sector": "Finance"},
    {"symbol": "MMC", "name": "Marsh & McLennan", "sector": "Finance"},
    {"symbol": "AON", "name": "Aon plc", "sector": "Finance"},
    {"symbol": "AJG", "name": "Arthur J. Gallagher", "sector": "Finance"},
    {"symbol": "LMND", "name": "Lemonade Inc.", "sector": "Finance"},

    # ===== HEALTHCARE =====
    # Pharmaceuticals
    {"symbol": "JNJ", "name": "Johnson & Johnson", "sector": "Healthcare"},
    {"symbol": "PFE", "name": "Pfizer Inc.", "sector": "Healthcare"},
    {"symbol": "MRK", "name": "Merck & Co.", "sector": "Healthcare"},
    {"symbol": "ABBV", "name": "AbbVie Inc.", "sector": "Healthcare"},
    {"symbol": "LLY", "name": "Eli Lilly", "sector": "Healthcare"},
    {"symbol": "BMY", "name": "Bristol-Myers Squibb", "sector": "Healthcare"},
    {"symbol": "AMGN", "name": "Amgen Inc.", "sector": "Healthcare"},
    {"symbol": "GILD", "name": "Gilead Sciences", "sector": "Healthcare"},
    {"symbol": "BIIB", "name": "Biogen Inc.", "sector": "Healthcare"},
    {"symbol": "REGN", "name": "Regeneron Pharmaceuticals", "sector": "Healthcare"},
    {"symbol": "VRTX", "name": "Vertex Pharmaceuticals", "sector": "Healthcare"},
    {"symbol": "AZN", "name": "AstraZeneca", "sector": "Healthcare"},
    {"symbol": "NVS", "name": "Novartis AG", "sector": "Healthcare"},
    {"symbol": "GSK", "name": "GSK plc", "sector": "Healthcare"},
    {"symbol": "SNY", "name": "Sanofi", "sector": "Healthcare"},
    {"symbol": "NVO", "name": "Novo Nordisk", "sector": "Healthcare"},
    {"symbol": "ZTS", "name": "Zoetis Inc.", "sector": "Healthcare"},

    # Biotech
    {"symbol": "MRNA", "name": "Moderna Inc.", "sector": "Healthcare"},
    {"symbol": "BNTX", "name": "BioNTech SE", "sector": "Healthcare"},
    {"symbol": "ILMN", "name": "Illumina Inc.", "sector": "Healthcare"},
    {"symbol": "ALNY", "name": "Alnylam Pharmaceuticals", "sector": "Healthcare"},
    {"symbol": "SGEN", "name": "Seagen Inc.", "sector": "Healthcare"},
    {"symbol": "BMRN", "name": "BioMarin Pharmaceutical", "sector": "Healthcare"},
    {"symbol": "EXAS", "name": "Exact Sciences", "sector": "Healthcare"},
    {"symbol": "INCY", "name": "Incyte Corporation", "sector": "Healthcare"},
    {"symbol": "SRPT", "name": "Sarepta Therapeutics", "sector": "Healthcare"},
    {"symbol": "NBIX", "name": "Neurocrine Biosciences", "sector": "Healthcare"},
    {"symbol": "ARGX", "name": "argenx SE", "sector": "Healthcare"},
    {"symbol": "PCVX", "name": "Vaxcyte Inc.", "sector": "Healthcare"},
    {"symbol": "CRSP", "name": "CRISPR Therapeutics", "sector": "Healthcare"},
    {"symbol": "NTLA", "name": "Intellia Therapeutics", "sector": "Healthcare"},
    {"symbol": "BEAM", "name": "Beam Therapeutics", "sector": "Healthcare"},
    {"symbol": "EDIT", "name": "Editas Medicine", "sector": "Healthcare"},

    # Medical Devices & Equipment
    {"symbol": "UNH", "name": "UnitedHealth Group", "sector": "Healthcare"},
    {"symbol": "CVS", "name": "CVS Health", "sector": "Healthcare"},
    {"symbol": "CI", "name": "Cigna Group", "sector": "Healthcare"},
    {"symbol": "ELV", "name": "Elevance Health", "sector": "Healthcare"},
    {"symbol": "HCA", "name": "HCA Healthcare", "sector": "Healthcare"},
    {"symbol": "ISRG", "name": "Intuitive Surgical", "sector": "Healthcare"},
    {"symbol": "MDT", "name": "Medtronic plc", "sector": "Healthcare"},
    {"symbol": "ABT", "name": "Abbott Laboratories", "sector": "Healthcare"},
    {"symbol": "DHR", "name": "Danaher Corporation", "sector": "Healthcare"},
    {"symbol": "TMO", "name": "Thermo Fisher Scientific", "sector": "Healthcare"},
    {"symbol": "SYK", "name": "Stryker Corporation", "sector": "Healthcare"},
    {"symbol": "BSX", "name": "Boston Scientific", "sector": "Healthcare"},
    {"symbol": "EW", "name": "Edwards Lifesciences", "sector": "Healthcare"},
    {"symbol": "BDX", "name": "Becton Dickinson", "sector": "Healthcare"},
    {"symbol": "DXCM", "name": "DexCom Inc.", "sector": "Healthcare"},
    {"symbol": "PODD", "name": "Insulet Corporation", "sector": "Healthcare"},
    {"symbol": "ALGN", "name": "Align Technology", "sector": "Healthcare"},
    {"symbol": "HOLX", "name": "Hologic Inc.", "sector": "Healthcare"},
    {"symbol": "IDXX", "name": "IDEXX Laboratories", "sector": "Healthcare"},
    {"symbol": "IQV", "name": "IQVIA Holdings", "sector": "Healthcare"},
    {"symbol": "A", "name": "Agilent Technologies", "sector": "Healthcare"},
    {"symbol": "WAT", "name": "Waters Corporation", "sector": "Healthcare"},
    {"symbol": "MTD", "name": "Mettler-Toledo", "sector": "Healthcare"},
    {"symbol": "TECH", "name": "Bio-Techne Corp", "sector": "Healthcare"},

    # ===== CONSUMER =====
    # Retail
    {"symbol": "WMT", "name": "Walmart Inc.", "sector": "Retail"},
    {"symbol": "COST", "name": "Costco Wholesale", "sector": "Retail"},
    {"symbol": "TGT", "name": "Target Corporation", "sector": "Retail"},
    {"symbol": "HD", "name": "Home Depot", "sector": "Retail"},
    {"symbol": "LOW", "name": "Lowe's Companies", "sector": "Retail"},
    {"symbol": "TJX", "name": "TJX Companies", "sector": "Retail"},
    {"symbol": "ROST", "name": "Ross Stores", "sector": "Retail"},
    {"symbol": "BURL", "name": "Burlington Stores", "sector": "Retail"},
    {"symbol": "DG", "name": "Dollar General", "sector": "Retail"},
    {"symbol": "DLTR", "name": "Dollar Tree", "sector": "Retail"},
    {"symbol": "BBY", "name": "Best Buy Co.", "sector": "Retail"},
    {"symbol": "ULTA", "name": "Ulta Beauty", "sector": "Retail"},
    {"symbol": "FIVE", "name": "Five Below", "sector": "Retail"},
    {"symbol": "ORLY", "name": "O'Reilly Automotive", "sector": "Retail"},
    {"symbol": "AZO", "name": "AutoZone Inc.", "sector": "Retail"},
    {"symbol": "AAP", "name": "Advance Auto Parts", "sector": "Retail"},
    {"symbol": "KMX", "name": "CarMax Inc.", "sector": "Retail"},
    {"symbol": "CAVA", "name": "CAVA Group", "sector": "Retail"},
    {"symbol": "BOOT", "name": "Boot Barn Holdings", "sector": "Retail"},

    # Consumer Brands
    {"symbol": "NKE", "name": "Nike Inc.", "sector": "Consumer"},
    {"symbol": "LULU", "name": "Lululemon Athletica", "sector": "Consumer"},
    {"symbol": "UAA", "name": "Under Armour", "sector": "Consumer"},
    {"symbol": "VFC", "name": "V.F. Corporation", "sector": "Consumer"},
    {"symbol": "PVH", "name": "PVH Corp.", "sector": "Consumer"},
    {"symbol": "RL", "name": "Ralph Lauren", "sector": "Consumer"},
    {"symbol": "TPR", "name": "Tapestry Inc.", "sector": "Consumer"},
    {"symbol": "CPRI", "name": "Capri Holdings", "sector": "Consumer"},
    {"symbol": "DECK", "name": "Deckers Outdoor", "sector": "Consumer"},
    {"symbol": "CROX", "name": "Crocs Inc.", "sector": "Consumer"},
    {"symbol": "SKX", "name": "Skechers U.S.A.", "sector": "Consumer"},
    {"symbol": "HBI", "name": "Hanesbrands Inc.", "sector": "Consumer"},
    {"symbol": "GPS", "name": "Gap Inc.", "sector": "Consumer"},
    {"symbol": "ANF", "name": "Abercrombie & Fitch", "sector": "Consumer"},
    {"symbol": "AEO", "name": "American Eagle Outfitters", "sector": "Consumer"},

    # Food & Beverage
    {"symbol": "KO", "name": "Coca-Cola Company", "sector": "Consumer"},
    {"symbol": "PEP", "name": "PepsiCo Inc.", "sector": "Consumer"},
    {"symbol": "SBUX", "name": "Starbucks Corporation", "sector": "Consumer"},
    {"symbol": "MCD", "name": "McDonald's Corporation", "sector": "Consumer"},
    {"symbol": "YUM", "name": "Yum! Brands", "sector": "Consumer"},
    {"symbol": "CMG", "name": "Chipotle Mexican Grill", "sector": "Consumer"},
    {"symbol": "DPZ", "name": "Domino's Pizza", "sector": "Consumer"},
    {"symbol": "DNUT", "name": "Krispy Kreme", "sector": "Consumer"},
    {"symbol": "QSR", "name": "Restaurant Brands Int'l", "sector": "Consumer"},
    {"symbol": "DRI", "name": "Darden Restaurants", "sector": "Consumer"},
    {"symbol": "TXRH", "name": "Texas Roadhouse", "sector": "Consumer"},
    {"symbol": "WING", "name": "Wingstop Inc.", "sector": "Consumer"},
    {"symbol": "SHAK", "name": "Shake Shack", "sector": "Consumer"},
    {"symbol": "BROS", "name": "Dutch Bros Inc.", "sector": "Consumer"},
    {"symbol": "MDLZ", "name": "Mondelez International", "sector": "Consumer"},
    {"symbol": "HSY", "name": "Hershey Company", "sector": "Consumer"},
    {"symbol": "K", "name": "Kellanova", "sector": "Consumer"},
    {"symbol": "GIS", "name": "General Mills", "sector": "Consumer"},
    {"symbol": "CAG", "name": "Conagra Brands", "sector": "Consumer"},
    {"symbol": "CPB", "name": "Campbell Soup", "sector": "Consumer"},
    {"symbol": "SJM", "name": "J.M. Smucker", "sector": "Consumer"},
    {"symbol": "HRL", "name": "Hormel Foods", "sector": "Consumer"},
    {"symbol": "TSN", "name": "Tyson Foods", "sector": "Consumer"},
    {"symbol": "BG", "name": "Bunge Limited", "sector": "Consumer"},
    {"symbol": "ADM", "name": "Archer-Daniels-Midland", "sector": "Consumer"},
    {"symbol": "KHC", "name": "Kraft Heinz", "sector": "Consumer"},
    {"symbol": "MNST", "name": "Monster Beverage", "sector": "Consumer"},
    {"symbol": "STZ", "name": "Constellation Brands", "sector": "Consumer"},
    {"symbol": "BF.B", "name": "Brown-Forman", "sector": "Consumer"},
    {"symbol": "TAP", "name": "Molson Coors", "sector": "Consumer"},
    {"symbol": "SAM", "name": "Boston Beer Company", "sector": "Consumer"},
    {"symbol": "CELH", "name": "Celsius Holdings", "sector": "Consumer"},

    # Household & Personal Care
    {"symbol": "PG", "name": "Procter & Gamble", "sector": "Consumer"},
    {"symbol": "CL", "name": "Colgate-Palmolive", "sector": "Consumer"},
    {"symbol": "KMB", "name": "Kimberly-Clark", "sector": "Consumer"},
    {"symbol": "CHD", "name": "Church & Dwight", "sector": "Consumer"},
    {"symbol": "CLX", "name": "Clorox Company", "sector": "Consumer"},
    {"symbol": "EL", "name": "Estee Lauder", "sector": "Consumer"},
    {"symbol": "ELF", "name": "e.l.f. Beauty", "sector": "Consumer"},

    # ===== ENTERTAINMENT & MEDIA =====
    {"symbol": "DIS", "name": "Walt Disney Company", "sector": "Entertainment"},
    {"symbol": "CMCSA", "name": "Comcast Corporation", "sector": "Entertainment"},
    {"symbol": "WBD", "name": "Warner Bros. Discovery", "sector": "Entertainment"},
    {"symbol": "PARA", "name": "Paramount Global", "sector": "Entertainment"},
    {"symbol": "NWSA", "name": "News Corp Class A", "sector": "Entertainment"},
    {"symbol": "FOX", "name": "Fox Corporation", "sector": "Entertainment"},
    {"symbol": "LYV", "name": "Live Nation Entertainment", "sector": "Entertainment"},
    {"symbol": "MSGS", "name": "Madison Square Garden Sports", "sector": "Entertainment"},
    {"symbol": "EA", "name": "Electronic Arts", "sector": "Entertainment"},
    {"symbol": "TTWO", "name": "Take-Two Interactive", "sector": "Entertainment"},
    {"symbol": "ATVI", "name": "Activision Blizzard", "sector": "Entertainment"},
    {"symbol": "SE", "name": "Sea Limited", "sector": "Entertainment"},
    {"symbol": "BILI", "name": "Bilibili Inc.", "sector": "Entertainment"},
    {"symbol": "ROKU", "name": "Roku Inc.", "sector": "Entertainment"},
    {"symbol": "FUBO", "name": "fuboTV Inc.", "sector": "Entertainment"},
    {"symbol": "SIRI", "name": "Sirius XM Holdings", "sector": "Entertainment"},
    {"symbol": "IMAX", "name": "IMAX Corporation", "sector": "Entertainment"},
    {"symbol": "CNK", "name": "Cinemark Holdings", "sector": "Entertainment"},
    {"symbol": "AMC", "name": "AMC Entertainment", "sector": "Entertainment"},
    {"symbol": "GME", "name": "GameStop Corp.", "sector": "Entertainment"},

    # ===== ENERGY =====
    # Oil & Gas
    {"symbol": "XOM", "name": "Exxon Mobil", "sector": "Energy"},
    {"symbol": "CVX", "name": "Chevron Corporation", "sector": "Energy"},
    {"symbol": "COP", "name": "ConocoPhillips", "sector": "Energy"},
    {"symbol": "EOG", "name": "EOG Resources", "sector": "Energy"},
    {"symbol": "SLB", "name": "Schlumberger", "sector": "Energy"},
    {"symbol": "OXY", "name": "Occidental Petroleum", "sector": "Energy"},
    {"symbol": "PXD", "name": "Pioneer Natural Resources", "sector": "Energy"},
    {"symbol": "DVN", "name": "Devon Energy", "sector": "Energy"},
    {"symbol": "MPC", "name": "Marathon Petroleum", "sector": "Energy"},
    {"symbol": "VLO", "name": "Valero Energy", "sector": "Energy"},
    {"symbol": "PSX", "name": "Phillips 66", "sector": "Energy"},
    {"symbol": "HES", "name": "Hess Corporation", "sector": "Energy"},
    {"symbol": "HAL", "name": "Halliburton Company", "sector": "Energy"},
    {"symbol": "BKR", "name": "Baker Hughes", "sector": "Energy"},
    {"symbol": "FANG", "name": "Diamondback Energy", "sector": "Energy"},
    {"symbol": "MRO", "name": "Marathon Oil", "sector": "Energy"},
    {"symbol": "APA", "name": "APA Corporation", "sector": "Energy"},
    {"symbol": "OVV", "name": "Ovintiv Inc.", "sector": "Energy"},
    {"symbol": "CTRA", "name": "Coterra Energy", "sector": "Energy"},
    {"symbol": "AR", "name": "Antero Resources", "sector": "Energy"},
    {"symbol": "RRC", "name": "Range Resources", "sector": "Energy"},
    {"symbol": "SWN", "name": "Southwestern Energy", "sector": "Energy"},
    {"symbol": "EQT", "name": "EQT Corporation", "sector": "Energy"},
    {"symbol": "KMI", "name": "Kinder Morgan", "sector": "Energy"},
    {"symbol": "WMB", "name": "Williams Companies", "sector": "Energy"},
    {"symbol": "OKE", "name": "ONEOK Inc.", "sector": "Energy"},
    {"symbol": "ET", "name": "Energy Transfer", "sector": "Energy"},
    {"symbol": "EPD", "name": "Enterprise Products", "sector": "Energy"},
    {"symbol": "MPLX", "name": "MPLX LP", "sector": "Energy"},

    # Clean Energy
    {"symbol": "NEE", "name": "NextEra Energy", "sector": "Energy"},
    {"symbol": "ENPH", "name": "Enphase Energy", "sector": "Energy"},
    {"symbol": "SEDG", "name": "SolarEdge Technologies", "sector": "Energy"},
    {"symbol": "FSLR", "name": "First Solar", "sector": "Energy"},
    {"symbol": "RUN", "name": "Sunrun Inc.", "sector": "Energy"},
    {"symbol": "NOVA", "name": "Sunnova Energy", "sector": "Energy"},
    {"symbol": "PLUG", "name": "Plug Power", "sector": "Energy"},
    {"symbol": "BE", "name": "Bloom Energy", "sector": "Energy"},
    {"symbol": "BLDP", "name": "Ballard Power Systems", "sector": "Energy"},
    {"symbol": "CHPT", "name": "ChargePoint Holdings", "sector": "Energy"},
    {"symbol": "EVGO", "name": "EVgo Inc.", "sector": "Energy"},
    {"symbol": "BLNK", "name": "Blink Charging", "sector": "Energy"},
    {"symbol": "VST", "name": "Vistra Corp.", "sector": "Energy"},
    {"symbol": "CEG", "name": "Constellation Energy", "sector": "Energy"},
    {"symbol": "NRG", "name": "NRG Energy", "sector": "Energy"},

    # ===== INDUSTRIALS =====
    # Aerospace & Defense
    {"symbol": "BA", "name": "Boeing Company", "sector": "Industrials"},
    {"symbol": "LMT", "name": "Lockheed Martin", "sector": "Industrials"},
    {"symbol": "RTX", "name": "RTX Corporation", "sector": "Industrials"},
    {"symbol": "NOC", "name": "Northrop Grumman", "sector": "Industrials"},
    {"symbol": "GD", "name": "General Dynamics", "sector": "Industrials"},
    {"symbol": "LHX", "name": "L3Harris Technologies", "sector": "Industrials"},
    {"symbol": "TDG", "name": "TransDigm Group", "sector": "Industrials"},
    {"symbol": "HWM", "name": "Howmet Aerospace", "sector": "Industrials"},
    {"symbol": "HII", "name": "Huntington Ingalls", "sector": "Industrials"},
    {"symbol": "TXT", "name": "Textron Inc.", "sector": "Industrials"},
    {"symbol": "AXON", "name": "Axon Enterprise", "sector": "Industrials"},
    {"symbol": "RKLB", "name": "Rocket Lab USA", "sector": "Industrials"},
    {"symbol": "SPCE", "name": "Virgin Galactic", "sector": "Industrials"},

    # Machinery & Equipment
    {"symbol": "CAT", "name": "Caterpillar Inc.", "sector": "Industrials"},
    {"symbol": "DE", "name": "Deere & Company", "sector": "Industrials"},
    {"symbol": "HON", "name": "Honeywell International", "sector": "Industrials"},
    {"symbol": "GE", "name": "GE Aerospace", "sector": "Industrials"},
    {"symbol": "MMM", "name": "3M Company", "sector": "Industrials"},
    {"symbol": "EMR", "name": "Emerson Electric", "sector": "Industrials"},
    {"symbol": "ETN", "name": "Eaton Corporation", "sector": "Industrials"},
    {"symbol": "ITW", "name": "Illinois Tool Works", "sector": "Industrials"},
    {"symbol": "PH", "name": "Parker-Hannifin", "sector": "Industrials"},
    {"symbol": "ROK", "name": "Rockwell Automation", "sector": "Industrials"},
    {"symbol": "DOV", "name": "Dover Corporation", "sector": "Industrials"},
    {"symbol": "CMI", "name": "Cummins Inc.", "sector": "Industrials"},
    {"symbol": "PCAR", "name": "PACCAR Inc.", "sector": "Industrials"},
    {"symbol": "IR", "name": "Ingersoll Rand", "sector": "Industrials"},
    {"symbol": "GNRC", "name": "Generac Holdings", "sector": "Industrials"},
    {"symbol": "XYL", "name": "Xylem Inc.", "sector": "Industrials"},
    {"symbol": "IEX", "name": "IDEX Corporation", "sector": "Industrials"},
    {"symbol": "OTIS", "name": "Otis Worldwide", "sector": "Industrials"},
    {"symbol": "CARR", "name": "Carrier Global", "sector": "Industrials"},

    # Logistics & Transportation
    {"symbol": "UPS", "name": "United Parcel Service", "sector": "Industrials"},
    {"symbol": "FDX", "name": "FedEx Corporation", "sector": "Industrials"},
    {"symbol": "UNP", "name": "Union Pacific", "sector": "Industrials"},
    {"symbol": "CSX", "name": "CSX Corporation", "sector": "Industrials"},
    {"symbol": "NSC", "name": "Norfolk Southern", "sector": "Industrials"},
    {"symbol": "CNI", "name": "Canadian National Railway", "sector": "Industrials"},
    {"symbol": "CP", "name": "Canadian Pacific Kansas City", "sector": "Industrials"},
    {"symbol": "GWW", "name": "W.W. Grainger", "sector": "Industrials"},
    {"symbol": "FAST", "name": "Fastenal Company", "sector": "Industrials"},
    {"symbol": "CHRW", "name": "C.H. Robinson", "sector": "Industrials"},
    {"symbol": "EXPD", "name": "Expeditors International", "sector": "Industrials"},
    {"symbol": "XPO", "name": "XPO Inc.", "sector": "Industrials"},
    {"symbol": "JBHT", "name": "J.B. Hunt Transport", "sector": "Industrials"},
    {"symbol": "ODFL", "name": "Old Dominion Freight", "sector": "Industrials"},
    {"symbol": "SAIA", "name": "Saia Inc.", "sector": "Industrials"},

    # Airlines
    {"symbol": "DAL", "name": "Delta Air Lines", "sector": "Industrials"},
    {"symbol": "UAL", "name": "United Airlines", "sector": "Industrials"},
    {"symbol": "AAL", "name": "American Airlines", "sector": "Industrials"},
    {"symbol": "LUV", "name": "Southwest Airlines", "sector": "Industrials"},
    {"symbol": "ALK", "name": "Alaska Air Group", "sector": "Industrials"},
    {"symbol": "JBLU", "name": "JetBlue Airways", "sector": "Industrials"},
    {"symbol": "SAVE", "name": "Spirit Airlines", "sector": "Industrials"},

    # ===== MATERIALS =====
    {"symbol": "LIN", "name": "Linde plc", "sector": "Materials"},
    {"symbol": "APD", "name": "Air Products & Chemicals", "sector": "Materials"},
    {"symbol": "SHW", "name": "Sherwin-Williams", "sector": "Materials"},
    {"symbol": "ECL", "name": "Ecolab Inc.", "sector": "Materials"},
    {"symbol": "DD", "name": "DuPont de Nemours", "sector": "Materials"},
    {"symbol": "DOW", "name": "Dow Inc.", "sector": "Materials"},
    {"symbol": "LYB", "name": "LyondellBasell Industries", "sector": "Materials"},
    {"symbol": "PPG", "name": "PPG Industries", "sector": "Materials"},
    {"symbol": "FCX", "name": "Freeport-McMoRan", "sector": "Materials"},
    {"symbol": "NUE", "name": "Nucor Corporation", "sector": "Materials"},
    {"symbol": "STLD", "name": "Steel Dynamics", "sector": "Materials"},
    {"symbol": "CLF", "name": "Cleveland-Cliffs", "sector": "Materials"},
    {"symbol": "X", "name": "United States Steel", "sector": "Materials"},
    {"symbol": "AA", "name": "Alcoa Corporation", "sector": "Materials"},
    {"symbol": "NEM", "name": "Newmont Corporation", "sector": "Materials"},
    {"symbol": "GOLD", "name": "Barrick Gold", "sector": "Materials"},
    {"symbol": "FNV", "name": "Franco-Nevada", "sector": "Materials"},
    {"symbol": "WPM", "name": "Wheaton Precious Metals", "sector": "Materials"},
    {"symbol": "RGLD", "name": "Royal Gold", "sector": "Materials"},
    {"symbol": "AEM", "name": "Agnico Eagle Mines", "sector": "Materials"},
    {"symbol": "KGC", "name": "Kinross Gold", "sector": "Materials"},
    {"symbol": "BTG", "name": "B2Gold Corp", "sector": "Materials"},
    {"symbol": "MOS", "name": "Mosaic Company", "sector": "Materials"},
    {"symbol": "CF", "name": "CF Industries", "sector": "Materials"},
    {"symbol": "NTR", "name": "Nutrien Ltd.", "sector": "Materials"},
    {"symbol": "FMC", "name": "FMC Corporation", "sector": "Materials"},
    {"symbol": "ALB", "name": "Albemarle Corporation", "sector": "Materials"},
    {"symbol": "LTHM", "name": "Livent Corporation", "sector": "Materials"},
    {"symbol": "LAC", "name": "Lithium Americas", "sector": "Materials"},
    {"symbol": "MP", "name": "MP Materials", "sector": "Materials"},

    # ===== REAL ESTATE =====
    {"symbol": "AMT", "name": "American Tower", "sector": "Real Estate"},
    {"symbol": "PLD", "name": "Prologis Inc.", "sector": "Real Estate"},
    {"symbol": "CCI", "name": "Crown Castle", "sector": "Real Estate"},
    {"symbol": "EQIX", "name": "Equinix Inc.", "sector": "Real Estate"},
    {"symbol": "PSA", "name": "Public Storage", "sector": "Real Estate"},
    {"symbol": "SPG", "name": "Simon Property Group", "sector": "Real Estate"},
    {"symbol": "DLR", "name": "Digital Realty Trust", "sector": "Real Estate"},
    {"symbol": "O", "name": "Realty Income", "sector": "Real Estate"},
    {"symbol": "VICI", "name": "VICI Properties", "sector": "Real Estate"},
    {"symbol": "WELL", "name": "Welltower Inc.", "sector": "Real Estate"},
    {"symbol": "AVB", "name": "AvalonBay Communities", "sector": "Real Estate"},
    {"symbol": "EQR", "name": "Equity Residential", "sector": "Real Estate"},
    {"symbol": "MAA", "name": "Mid-America Apartment", "sector": "Real Estate"},
    {"symbol": "UDR", "name": "UDR Inc.", "sector": "Real Estate"},
    {"symbol": "ESS", "name": "Essex Property Trust", "sector": "Real Estate"},
    {"symbol": "INVH", "name": "Invitation Homes", "sector": "Real Estate"},
    {"symbol": "SUI", "name": "Sun Communities", "sector": "Real Estate"},
    {"symbol": "ELS", "name": "Equity LifeStyle", "sector": "Real Estate"},
    {"symbol": "ARE", "name": "Alexandria Real Estate", "sector": "Real Estate"},
    {"symbol": "BXP", "name": "Boston Properties", "sector": "Real Estate"},
    {"symbol": "KIM", "name": "Kimco Realty", "sector": "Real Estate"},
    {"symbol": "REG", "name": "Regency Centers", "sector": "Real Estate"},
    {"symbol": "FRT", "name": "Federal Realty", "sector": "Real Estate"},
    {"symbol": "VTR", "name": "Ventas Inc.", "sector": "Real Estate"},
    {"symbol": "PEAK", "name": "Healthpeak Properties", "sector": "Real Estate"},
    {"symbol": "SBAC", "name": "SBA Communications", "sector": "Real Estate"},
    {"symbol": "IRM", "name": "Iron Mountain", "sector": "Real Estate"},

    # ===== UTILITIES =====
    {"symbol": "NEE", "name": "NextEra Energy", "sector": "Utilities"},
    {"symbol": "DUK", "name": "Duke Energy", "sector": "Utilities"},
    {"symbol": "SO", "name": "Southern Company", "sector": "Utilities"},
    {"symbol": "D", "name": "Dominion Energy", "sector": "Utilities"},
    {"symbol": "AEP", "name": "American Electric Power", "sector": "Utilities"},
    {"symbol": "SRE", "name": "Sempra", "sector": "Utilities"},
    {"symbol": "EXC", "name": "Exelon Corporation", "sector": "Utilities"},
    {"symbol": "XEL", "name": "Xcel Energy", "sector": "Utilities"},
    {"symbol": "ED", "name": "Consolidated Edison", "sector": "Utilities"},
    {"symbol": "WEC", "name": "WEC Energy Group", "sector": "Utilities"},
    {"symbol": "ES", "name": "Eversource Energy", "sector": "Utilities"},
    {"symbol": "EIX", "name": "Edison International", "sector": "Utilities"},
    {"symbol": "PCG", "name": "PG&E Corporation", "sector": "Utilities"},
    {"symbol": "PPL", "name": "PPL Corporation", "sector": "Utilities"},
    {"symbol": "FE", "name": "FirstEnergy Corp", "sector": "Utilities"},
    {"symbol": "DTE", "name": "DTE Energy", "sector": "Utilities"},
    {"symbol": "ETR", "name": "Entergy Corporation", "sector": "Utilities"},
    {"symbol": "AES", "name": "AES Corporation", "sector": "Utilities"},
    {"symbol": "CMS", "name": "CMS Energy", "sector": "Utilities"},
    {"symbol": "AEE", "name": "Ameren Corporation", "sector": "Utilities"},
    {"symbol": "AWK", "name": "American Water Works", "sector": "Utilities"},

    # ===== TELECOM =====
    {"symbol": "T", "name": "AT&T Inc.", "sector": "Telecom"},
    {"symbol": "VZ", "name": "Verizon Communications", "sector": "Telecom"},
    {"symbol": "TMUS", "name": "T-Mobile US", "sector": "Telecom"},
    {"symbol": "CHTR", "name": "Charter Communications", "sector": "Telecom"},
    {"symbol": "LBRDA", "name": "Liberty Broadband A", "sector": "Telecom"},
    {"symbol": "LBRDK", "name": "Liberty Broadband K", "sector": "Telecom"},
    {"symbol": "LUMN", "name": "Lumen Technologies", "sector": "Telecom"},
    {"symbol": "FYBR", "name": "Frontier Communications", "sector": "Telecom"},

    # ===== ETFs =====
    {"symbol": "SPY", "name": "SPDR S&P 500 ETF", "sector": "ETF"},
    {"symbol": "QQQ", "name": "Invesco QQQ Trust (NASDAQ 100)", "sector": "ETF"},
    {"symbol": "IWM", "name": "iShares Russell 2000", "sector": "ETF"},
    {"symbol": "DIA", "name": "SPDR Dow Jones Industrial", "sector": "ETF"},
    {"symbol": "VTI", "name": "Vanguard Total Stock Market", "sector": "ETF"},
    {"symbol": "VOO", "name": "Vanguard S&P 500", "sector": "ETF"},
    {"symbol": "VUG", "name": "Vanguard Growth", "sector": "ETF"},
    {"symbol": "VTV", "name": "Vanguard Value", "sector": "ETF"},
    {"symbol": "VGT", "name": "Vanguard Information Technology", "sector": "ETF"},
    {"symbol": "VHT", "name": "Vanguard Health Care", "sector": "ETF"},
    {"symbol": "VFH", "name": "Vanguard Financials", "sector": "ETF"},
    {"symbol": "VDE", "name": "Vanguard Energy", "sector": "ETF"},
    {"symbol": "VNQ", "name": "Vanguard Real Estate", "sector": "ETF"},
    {"symbol": "ARKK", "name": "ARK Innovation ETF", "sector": "ETF"},
    {"symbol": "ARKW", "name": "ARK Next Gen Internet", "sector": "ETF"},
    {"symbol": "ARKF", "name": "ARK Fintech Innovation", "sector": "ETF"},
    {"symbol": "ARKG", "name": "ARK Genomic Revolution", "sector": "ETF"},
    {"symbol": "ARKQ", "name": "ARK Autonomous Tech & Robotics", "sector": "ETF"},
    {"symbol": "XLK", "name": "Technology Select Sector SPDR", "sector": "ETF"},
    {"symbol": "XLF", "name": "Financial Select Sector SPDR", "sector": "ETF"},
    {"symbol": "XLV", "name": "Health Care Select Sector SPDR", "sector": "ETF"},
    {"symbol": "XLE", "name": "Energy Select Sector SPDR", "sector": "ETF"},
    {"symbol": "XLY", "name": "Consumer Discretionary SPDR", "sector": "ETF"},
    {"symbol": "XLP", "name": "Consumer Staples SPDR", "sector": "ETF"},
    {"symbol": "XLI", "name": "Industrial Select Sector SPDR", "sector": "ETF"},
    {"symbol": "XLB", "name": "Materials Select Sector SPDR", "sector": "ETF"},
    {"symbol": "XLU", "name": "Utilities Select Sector SPDR", "sector": "ETF"},
    {"symbol": "XLRE", "name": "Real Estate Select Sector SPDR", "sector": "ETF"},
    {"symbol": "SMH", "name": "VanEck Semiconductor ETF", "sector": "ETF"},
    {"symbol": "SOXX", "name": "iShares Semiconductor ETF", "sector": "ETF"},
    {"symbol": "IBB", "name": "iShares Biotechnology ETF", "sector": "ETF"},
    {"symbol": "XBI", "name": "SPDR S&P Biotech ETF", "sector": "ETF"},
    {"symbol": "GDX", "name": "VanEck Gold Miners ETF", "sector": "ETF"},
    {"symbol": "GDXJ", "name": "VanEck Junior Gold Miners", "sector": "ETF"},
    {"symbol": "SLV", "name": "iShares Silver Trust", "sector": "ETF"},
    {"symbol": "GLD", "name": "SPDR Gold Shares", "sector": "ETF"},
    {"symbol": "USO", "name": "United States Oil Fund", "sector": "ETF"},
    {"symbol": "UNG", "name": "United States Natural Gas Fund", "sector": "ETF"},
    {"symbol": "TAN", "name": "Invesco Solar ETF", "sector": "ETF"},
    {"symbol": "ICLN", "name": "iShares Global Clean Energy", "sector": "ETF"},
    {"symbol": "LIT", "name": "Global X Lithium & Battery Tech", "sector": "ETF"},
    {"symbol": "BOTZ", "name": "Global X Robotics & AI ETF", "sector": "ETF"},
    {"symbol": "ROBO", "name": "Robo Global Robotics & Auto ETF", "sector": "ETF"},
    {"symbol": "HACK", "name": "ETFMG Prime Cyber Security", "sector": "ETF"},
    {"symbol": "CIBR", "name": "First Trust Cybersecurity ETF", "sector": "ETF"},
    {"symbol": "FINX", "name": "Global X FinTech ETF", "sector": "ETF"},
    {"symbol": "BLOK", "name": "Amplify Transformational Data", "sector": "ETF"},
    {"symbol": "BITO", "name": "ProShares Bitcoin Strategy ETF", "sector": "ETF"},
    {"symbol": "IBIT", "name": "iShares Bitcoin Trust", "sector": "ETF"},
    {"symbol": "GBTC", "name": "Grayscale Bitcoin Trust", "sector": "ETF"},
    {"symbol": "ETHE", "name": "Grayscale Ethereum Trust", "sector": "ETF"},
    {"symbol": "SOXL", "name": "Direxion Semiconductor Bull 3X", "sector": "ETF"},
    {"symbol": "SOXS", "name": "Direxion Semiconductor Bear 3X", "sector": "ETF"},
    {"symbol": "TQQQ", "name": "ProShares UltraPro QQQ 3X", "sector": "ETF"},
    {"symbol": "SQQQ", "name": "ProShares UltraPro Short QQQ 3X", "sector": "ETF"},
    {"symbol": "SPXU", "name": "ProShares UltraPro Short S&P 500", "sector": "ETF"},
    {"symbol": "UPRO", "name": "ProShares UltraPro S&P 500", "sector": "ETF"},
    {"symbol": "UVXY", "name": "ProShares Ultra VIX Short-Term", "sector": "ETF"},
    {"symbol": "SVXY", "name": "ProShares Short VIX Short-Term", "sector": "ETF"},
    {"symbol": "VXX", "name": "iPath Series B S&P 500 VIX", "sector": "ETF"},
    {"symbol": "EEM", "name": "iShares MSCI Emerging Markets", "sector": "ETF"},
    {"symbol": "EFA", "name": "iShares MSCI EAFE", "sector": "ETF"},
    {"symbol": "VWO", "name": "Vanguard FTSE Emerging Markets", "sector": "ETF"},
    {"symbol": "VXUS", "name": "Vanguard Total International Stock", "sector": "ETF"},
    {"symbol": "FXI", "name": "iShares China Large-Cap", "sector": "ETF"},
    {"symbol": "KWEB", "name": "KraneShares CSI China Internet", "sector": "ETF"},
    {"symbol": "EWJ", "name": "iShares MSCI Japan", "sector": "ETF"},
    {"symbol": "EWG", "name": "iShares MSCI Germany", "sector": "ETF"},
    {"symbol": "EWU", "name": "iShares MSCI United Kingdom", "sector": "ETF"},
    {"symbol": "TLT", "name": "iShares 20+ Year Treasury Bond", "sector": "ETF"},
    {"symbol": "IEF", "name": "iShares 7-10 Year Treasury Bond", "sector": "ETF"},
    {"symbol": "SHY", "name": "iShares 1-3 Year Treasury Bond", "sector": "ETF"},
    {"symbol": "BND", "name": "Vanguard Total Bond Market", "sector": "ETF"},
    {"symbol": "AGG", "name": "iShares Core US Aggregate Bond", "sector": "ETF"},
    {"symbol": "LQD", "name": "iShares Investment Grade Corporate Bond", "sector": "ETF"},
    {"symbol": "HYG", "name": "iShares High Yield Corporate Bond", "sector": "ETF"},
    {"symbol": "JNK", "name": "SPDR Bloomberg High Yield Bond", "sector": "ETF"},
]

# Technical Analysis Settings
TA_SETTINGS = {
    "rsi_period": 14,
    "rsi_overbought": 70,
    "rsi_oversold": 30,
    "macd_fast": 12,
    "macd_slow": 26,
    "macd_signal": 9,
    "sma_short": 20,
    "sma_long": 50,
    "ema_short": 12,
    "ema_long": 26,
    "bollinger_period": 20,
    "bollinger_std": 2,
}

# Signal Thresholds
SIGNAL_THRESHOLDS = {
    "strong_buy": 80,
    "buy": 60,
    "neutral_high": 55,
    "neutral_low": 45,
    "sell": 40,
    "strong_sell": 20,
}

# API Settings
API_SETTINGS = {
    "coingecko_base_url": "https://api.coingecko.com/api/v3",
    "cache_timeout": 60,  # seconds
    "rate_limit_delay": 1.5,  # seconds between API calls
}
